// repoguard:ignore-file — this file defines detection patterns, so it will
// naturally contain strings that look like the tokens we scan for.
import type { Severity } from "./types"

export type SecretPattern = {
  id: string
  name: string
  severity: Severity
  description: string
  regex: RegExp
}

/**
 * Curated secret detection patterns. Priority: high-confidence, widely-used
 * credential formats. Ordered roughly by blast-radius if leaked (cloud infra
 * first, then generic credentials, then data/comms services).
 */
export const SECRET_PATTERNS: SecretPattern[] = [
  // ───── Cloud providers (highest blast radius) ─────
  {
    id: "aws-access-key",
    name: "AWS Access Key ID",
    severity: "critical",
    description: "Amazon Web Services access key. Grants programmatic access to AWS resources.",
    regex: /\b(AKIA|ASIA|AIDA|AROA|AGPA|ANPA|ANVA|ABIA|ACCA)[0-9A-Z]{16}\b/g,
  },
  {
    id: "aws-secret-key",
    name: "AWS Secret Access Key",
    severity: "critical",
    description: "AWS secret key paired with an access key ID. Full compromise if leaked.",
    regex: /\baws(.{0,20})?['"][0-9a-zA-Z/+]{40}['"]/gi,
  },
  {
    id: "aws-session-token",
    name: "AWS Session Token",
    severity: "critical",
    description: "Short-lived STS session token. High value while active.",
    regex: /\b(?:aws_session_token|AWS_SESSION_TOKEN)['":=\s]+['"][A-Za-z0-9/+=]{100,}['"]/g,
  },
  {
    id: "azure-client-secret",
    name: "Azure AD Client Secret",
    severity: "critical",
    description: "Azure Active Directory application client secret.",
    regex: /(?:azure|aad|client_secret|tenant)[\s\S]{0,60}?['"][A-Za-z0-9~._-]{34,40}['"]/gi,
  },
  {
    id: "azure-storage-key",
    name: "Azure Storage Account Key",
    severity: "critical",
    description: "Azure Storage account primary/secondary key. Grants full access to blobs/tables/queues.",
    regex: /\bDefaultEndpointsProtocol=https;AccountName=[a-z0-9]+;AccountKey=[A-Za-z0-9+/=]{88}\b/g,
  },
  {
    id: "gcp-service-account",
    name: "GCP Service Account Private Key",
    severity: "critical",
    description: "Google Cloud service account JSON private key. Often grants broad project access.",
    regex: /"type":\s*"service_account"[\s\S]{0,500}?"private_key":\s*"-----BEGIN PRIVATE KEY-----/g,
  },
  {
    id: "gcp-api-key",
    name: "Google Cloud / Firebase API Key",
    severity: "high",
    description: "Google Cloud / Firebase API key. Can incur usage costs and expose data.",
    regex: /\bAIza[0-9A-Za-z_-]{35}\b/g,
  },
  {
    id: "gcp-oauth-client-id",
    name: "Google OAuth Client ID + Secret",
    severity: "high",
    description: "Google OAuth client credentials for server-to-server flows.",
    regex: /\b[0-9]+-[a-z0-9]{32}\.apps\.googleusercontent\.com\b/g,
  },
  {
    id: "digitalocean-token",
    name: "DigitalOcean Personal Access Token",
    severity: "critical",
    description: "DigitalOcean API token. Full control over droplets, databases, Spaces.",
    regex: /\bdop_v1_[a-f0-9]{64}\b/g,
  },
  {
    id: "digitalocean-oauth",
    name: "DigitalOcean OAuth Token",
    severity: "critical",
    description: "DigitalOcean OAuth access/refresh token.",
    regex: /\bdo(?:o|r)_v1_[a-f0-9]{64}\b/g,
  },
  {
    id: "heroku-api-key",
    name: "Heroku API Key",
    severity: "critical",
    description: "Heroku platform API key. Can deploy code and access add-on data.",
    regex: /\bheroku[a-z0-9_ .\-,]{0,25}(?:=|:|token|key)[^\S\n]*['"]?[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}\b/gi,
  },
  {
    id: "cloudflare-api-token",
    name: "Cloudflare API Token",
    severity: "critical",
    description: "Cloudflare scoped API token. Can modify DNS, firewall, workers.",
    regex: /\b(?:cloudflare|cf)[-_. ]?(?:api[-_]?token|token)['":=\s]+['"]?[A-Za-z0-9_-]{40}['"]?/gi,
  },
  {
    id: "vercel-token",
    name: "Vercel API Token",
    severity: "critical",
    description: "Vercel personal access token. Can deploy and read env vars.",
    regex: /\b(?:vercel|vc)[-_. ]?(?:api[-_]?token|token)['":=\s]+['"]?[A-Za-z0-9]{24,}['"]?/gi,
  },
  {
    id: "netlify-token",
    name: "Netlify Personal Access Token",
    severity: "critical",
    description: "Netlify PAT. Full account access for sites, builds, team.",
    regex: /\bnfp_[A-Za-z0-9]{36,}\b/g,
  },
  {
    id: "render-api-key",
    name: "Render API Key",
    severity: "high",
    description: "Render platform API key.",
    regex: /\brnd_[A-Za-z0-9]{24,}\b/g,
  },
  {
    id: "flyio-token",
    name: "Fly.io API Token",
    severity: "critical",
    description: "Fly.io access token. Full org/app control.",
    regex: /\bfo1_[A-Za-z0-9_-]{40,}\b/g,
  },
  {
    id: "hashicorp-vault-token",
    name: "HashiCorp Vault Token",
    severity: "critical",
    description: "Vault auth token. Potential access to managed secrets.",
    regex: /\bhvs\.[A-Za-z0-9_-]{20,}\b/g,
  },
  {
    id: "terraform-cloud-token",
    name: "Terraform Cloud API Token",
    severity: "critical",
    description: "Terraform Cloud user/team API token. Can apply infra changes.",
    regex: /\b[A-Za-z0-9]{14}\.atlasv1\.[A-Za-z0-9_-]{60,}\b/g,
  },

  // ───── Source-code hosting (supply-chain critical) ─────
  {
    id: "github-pat",
    name: "GitHub Personal Access Token (classic)",
    severity: "critical",
    description: "Classic GitHub token granting repo, user, and potentially admin access.",
    regex: /\bghp_[A-Za-z0-9]{36}\b/g,
  },
  {
    id: "github-fine-grained-pat",
    name: "GitHub Fine-Grained Token",
    severity: "critical",
    description: "Newer GitHub token with scoped permissions.",
    regex: /\bgithub_pat_[A-Za-z0-9_]{82}\b/g,
  },
  {
    id: "github-oauth",
    name: "GitHub OAuth Access Token",
    severity: "critical",
    description: "OAuth access token issued by GitHub (user-to-server).",
    regex: /\bgho_[A-Za-z0-9]{36}\b/g,
  },
  {
    id: "github-user-to-server",
    name: "GitHub User-to-Server Token",
    severity: "critical",
    description: "GitHub App user access token.",
    regex: /\bghu_[A-Za-z0-9]{36}\b/g,
  },
  {
    id: "github-server-to-server",
    name: "GitHub Server-to-Server Token",
    severity: "critical",
    description: "GitHub App installation token. Short-lived but highly privileged.",
    regex: /\bghs_[A-Za-z0-9]{36}\b/g,
  },
  {
    id: "github-refresh",
    name: "GitHub Refresh Token",
    severity: "critical",
    description: "GitHub OAuth refresh token.",
    regex: /\bghr_[A-Za-z0-9]{76}\b/g,
  },
  {
    id: "gitlab-pat",
    name: "GitLab Personal Access Token",
    severity: "critical",
    description: "GitLab PAT. Scopes may include api/write_repository/admin.",
    regex: /\bglpat-[A-Za-z0-9_-]{20,}\b/g,
  },
  {
    id: "gitlab-runner-token",
    name: "GitLab Runner Registration Token",
    severity: "high",
    description: "GitLab CI runner registration token.",
    regex: /\bGR1348941[A-Za-z0-9_-]{20,}\b/g,
  },
  {
    id: "bitbucket-app-password",
    name: "Bitbucket App Password",
    severity: "high",
    description: "Bitbucket app password (ATBB-prefixed).",
    regex: /\bATBB[A-Za-z0-9]{32}\b/g,
  },

  // ───── AI providers (fast-growing category) ─────
  {
    id: "anthropic-api-key",
    name: "Anthropic API Key",
    severity: "critical",
    description: "Anthropic (Claude) API key. Incurs usage charges and grants model access.",
    regex: /\bsk-ant-(?:api|admin)\d{2}-[A-Za-z0-9_-]{80,}\b/g,
  },
  {
    id: "openai-api-key",
    name: "OpenAI API Key",
    severity: "critical",
    description: "OpenAI API key. Can incur significant usage charges.",
    regex: /\bsk-(?:proj-)?[A-Za-z0-9_-]{20,}T3BlbkFJ[A-Za-z0-9_-]{20,}\b/g,
  },
  {
    id: "openai-legacy-key",
    name: "OpenAI API Key (legacy)",
    severity: "critical",
    description: "Legacy OpenAI API key format.",
    regex: /\bsk-[A-Za-z0-9]{48}\b/g,
  },
  {
    id: "huggingface-token",
    name: "Hugging Face Access Token",
    severity: "high",
    description: "Hugging Face user access token. Can read private models/datasets.",
    regex: /\bhf_[A-Za-z0-9]{34,}\b/g,
  },
  {
    id: "replicate-api-token",
    name: "Replicate API Token",
    severity: "high",
    description: "Replicate.com API token for model inference.",
    regex: /\br8_[A-Za-z0-9]{37,}\b/g,
  },
  {
    id: "perplexity-api-key",
    name: "Perplexity API Key",
    severity: "high",
    description: "Perplexity.ai API key.",
    regex: /\bpplx-[A-Za-z0-9]{48,}\b/g,
  },
  {
    id: "groq-api-key",
    name: "Groq API Key",
    severity: "high",
    description: "Groq Cloud inference API key.",
    regex: /\bgsk_[A-Za-z0-9]{40,}\b/g,
  },

  // ───── Payments ─────
  {
    id: "stripe-live-secret",
    name: "Stripe Live Secret Key",
    severity: "critical",
    description: "Stripe production secret key. Can charge real cards.",
    regex: /\bsk_live_[0-9a-zA-Z]{24,}\b/g,
  },
  {
    id: "stripe-restricted-live",
    name: "Stripe Restricted Live Key",
    severity: "critical",
    description: "Stripe restricted key (rk_live_).",
    regex: /\brk_live_[0-9a-zA-Z]{24,}\b/g,
  },
  {
    id: "stripe-test-secret",
    name: "Stripe Test Secret Key",
    severity: "medium",
    description: "Stripe test key. Lower risk but still should not be public.",
    regex: /\bsk_test_[0-9a-zA-Z]{24,}\b/g,
  },
  {
    id: "stripe-publishable-live",
    name: "Stripe Publishable Live Key",
    severity: "low",
    description: "Stripe publishable key — meant to be public, but flagged for inventory.",
    regex: /\bpk_live_[0-9a-zA-Z]{24,}\b/g,
  },
  {
    id: "paypal-braintree-token",
    name: "Braintree (PayPal) Access Token",
    severity: "critical",
    description: "Braintree production access token.",
    regex: /\baccess_token\$production\$[a-z0-9]{16}\$[a-f0-9]{32}\b/g,
  },
  {
    id: "square-access-token",
    name: "Square Access Token",
    severity: "critical",
    description: "Square production OAuth access token.",
    regex: /\bsq0atp-[A-Za-z0-9_-]{22,}\b/g,
  },
  {
    id: "shopify-access-token",
    name: "Shopify Access Token",
    severity: "critical",
    description: "Shopify Admin API access token.",
    regex: /\bshpat_[a-fA-F0-9]{32,}\b/g,
  },
  {
    id: "shopify-shared-secret",
    name: "Shopify Shared Secret",
    severity: "high",
    description: "Shopify app shared secret.",
    regex: /\bshpss_[a-fA-F0-9]{32,}\b/g,
  },
  {
    id: "adyen-api-key",
    name: "Adyen API Key",
    severity: "critical",
    description: "Adyen payments API key.",
    regex: /\bAQE[A-Za-z0-9]{50,}\b/g,
  },

  // ───── Communications / email ─────
  {
    id: "slack-token",
    name: "Slack Token",
    severity: "high",
    description: "Slack bot, user, or workspace token (xoxb/xoxp/xoxa/xoxr/xoxs).",
    regex: /\bxox[baprs]-[0-9]{10,}-[0-9]{10,}-[0-9a-zA-Z]{24,}\b/g,
  },
  {
    id: "slack-webhook",
    name: "Slack Webhook URL",
    severity: "medium",
    description: "Slack incoming webhook. Allows posting to channels anonymously.",
    regex: /\bhttps:\/\/hooks\.slack\.com\/services\/T[A-Z0-9]+\/B[A-Z0-9]+\/[A-Za-z0-9]{24}\b/g,
  },
  {
    id: "discord-bot-token",
    name: "Discord Bot Token",
    severity: "high",
    description: "Discord bot token.",
    regex: /\b[MN][A-Za-z\d]{23}\.[\w-]{6}\.[\w-]{27}\b/g,
  },
  {
    id: "discord-webhook",
    name: "Discord Webhook URL",
    severity: "medium",
    description: "Discord webhook URL.",
    regex: /\bhttps:\/\/(?:discord|discordapp)\.com\/api\/webhooks\/\d+\/[A-Za-z0-9_-]+\b/g,
  },
  {
    id: "telegram-bot-token",
    name: "Telegram Bot Token",
    severity: "high",
    description: "Telegram Bot API token.",
    regex: /\b\d{9,10}:[A-Za-z0-9_-]{35}\b/g,
  },
  {
    id: "sendgrid-key",
    name: "SendGrid API Key",
    severity: "high",
    description: "SendGrid email API key.",
    regex: /\bSG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}\b/g,
  },
  {
    id: "mailgun-key",
    name: "Mailgun API Key",
    severity: "high",
    description: "Mailgun API key.",
    regex: /\bkey-[a-z0-9]{32}\b/g,
  },
  {
    id: "postmark-token",
    name: "Postmark Server Token",
    severity: "high",
    description: "Postmark server API token.",
    regex: /\bpostmark(?:.{0,30})?['"][0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}['"]/gi,
  },
  {
    id: "mailchimp-key",
    name: "Mailchimp API Key",
    severity: "high",
    description: "Mailchimp API key.",
    regex: /\b[a-f0-9]{32}-us[0-9]{1,2}\b/g,
  },
  {
    id: "twilio-account-sid",
    name: "Twilio Account SID",
    severity: "medium",
    description: "Twilio account SID (paired with auth token elsewhere).",
    regex: /\bAC[a-f0-9]{32}\b/g,
  },
  {
    id: "twilio-api-key",
    name: "Twilio API Key",
    severity: "high",
    description: "Twilio API key SID.",
    regex: /\bSK[a-f0-9]{32}\b/g,
  },

  // ───── Package registries & dev tooling ─────
  {
    id: "npm-access-token",
    name: "npm Access Token",
    severity: "critical",
    description: "npm granular/automation access token (publishing supply-chain risk).",
    regex: /\bnpm_[A-Za-z0-9]{36}\b/g,
  },
  {
    id: "pypi-token",
    name: "PyPI API Token",
    severity: "critical",
    description: "PyPI upload token (publishing supply-chain risk).",
    regex: /\bpypi-AgEIcHlwaS5vcmc[A-Za-z0-9_-]{50,}\b/g,
  },
  {
    id: "docker-hub-pat",
    name: "Docker Hub Personal Access Token",
    severity: "critical",
    description: "Docker Hub PAT. Can push images to any repo the user owns.",
    regex: /\bdckr_pat_[A-Za-z0-9_-]{27,}\b/g,
  },
  {
    id: "jfrog-access-token",
    name: "JFrog Access Token",
    severity: "high",
    description: "JFrog Artifactory access token.",
    regex: /\b(?:cm|ref)[kt]:[A-Za-z0-9_.-]{40,}\b/g,
  },
  {
    id: "circleci-token",
    name: "CircleCI Personal Token",
    severity: "high",
    description: "CircleCI API personal token.",
    regex: /\bCCIPAT_[A-Za-z0-9]{24,}_[A-Za-z0-9]{40}\b/g,
  },

  // ───── Monitoring / analytics ─────
  {
    id: "datadog-api-key",
    name: "Datadog API Key",
    severity: "high",
    description: "Datadog API key (32-char hex).",
    regex: /\b(?:datadog|dd)[-_. ]?(?:api[-_]?key)['":=\s]+['"]?[a-f0-9]{32}['"]?/gi,
  },
  {
    id: "datadog-app-key",
    name: "Datadog Application Key",
    severity: "high",
    description: "Datadog application key (40-char hex).",
    regex: /\b(?:datadog|dd)[-_. ]?app[-_]?key['":=\s]+['"]?[a-f0-9]{40}['"]?/gi,
  },
  {
    id: "newrelic-license",
    name: "New Relic License Key",
    severity: "high",
    description: "New Relic ingest license key (INSERT or USER).",
    regex: /\bNRAK-[A-Z0-9]{27}\b|\bNRII-[A-Za-z0-9_-]{32}\b/g,
  },
  {
    id: "sentry-dsn",
    name: "Sentry DSN (with secret)",
    severity: "medium",
    description: "Sentry DSN containing a secret key (legacy format).",
    regex: /\bhttps:\/\/[a-f0-9]{32}:[a-f0-9]{32}@[a-z0-9.-]+\/[0-9]+\b/g,
  },
  {
    id: "pagerduty-key",
    name: "PagerDuty API Key",
    severity: "high",
    description: "PagerDuty REST API key.",
    regex: /\b(?:pagerduty|pd)[-_. ]?(?:api[-_]?key|token)['":=\s]+['"]?[A-Za-z0-9_+\-]{20,32}['"]?/gi,
  },
  {
    id: "segment-write-key",
    name: "Segment Write Key",
    severity: "medium",
    description: "Segment.com source write key.",
    regex: /\b(?:segment)[-_. ]?(?:write[-_]?key)['":=\s]+['"]?[A-Za-z0-9]{32}['"]?/gi,
  },
  {
    id: "algolia-admin-key",
    name: "Algolia Admin API Key",
    severity: "critical",
    description: "Algolia admin API key (full control over indices).",
    regex: /\b(?:algolia)[-_. ]?(?:admin[-_]?(?:api[-_]?)?key)['":=\s]+['"]?[a-f0-9]{32}['"]?/gi,
  },

  // ───── Generic / high-confidence formats ─────
  {
    id: "private-key",
    name: "Private Key (RSA / SSH / PGP / EC)",
    severity: "critical",
    description: "Private cryptographic key material. Should never be committed.",
    regex: /-----BEGIN (RSA |DSA |EC |OPENSSH |ENCRYPTED |PGP )?PRIVATE KEY( BLOCK)?-----/g,
  },
  {
    id: "jwt",
    name: "JSON Web Token (JWT)",
    severity: "medium",
    description: "Possible JWT. May or may not be sensitive depending on contents.",
    regex: /\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b/g,
  },
  {
    id: "password-in-url",
    name: "Password in Connection String",
    severity: "high",
    description: "Database or service URL with embedded password.",
    regex: /\b(mongodb(?:\+srv)?|postgres|postgresql|mysql|mariadb|redis|rediss|amqp|amqps|ftp|sftp|ssh|ldap|ldaps):\/\/[^\s:@/]+:[^\s@/]+@[^\s]+/gi,
  },
  {
    id: "basic-auth-url",
    name: "HTTP Basic Auth in URL",
    severity: "high",
    description: "HTTP(S) URL with embedded username:password Basic Auth.",
    regex: /\bhttps?:\/\/[A-Za-z0-9._~%+-]{1,64}:[^\s/@]{6,}@[A-Za-z0-9.-]+\b/g,
  },
  {
    id: "npmrc-authtoken",
    name: ".npmrc _authToken",
    severity: "critical",
    description: "npm registry auth token inside .npmrc — often grants publish rights.",
    regex: /\/\/[^\s=]+\/:_authToken\s*=\s*[A-Za-z0-9_-]{10,}/g,
  },
  {
    id: "pypirc-password",
    name: ".pypirc Password",
    severity: "critical",
    description: "PyPI credentials in .pypirc — publish token or password.",
    regex: /\[pypi\][\s\S]{0,200}?password\s*=\s*\S+/g,
  },
  {
    id: "okta-api-token",
    name: "Okta API Token",
    severity: "critical",
    description: "Okta administrative API token.",
    regex: /(?:okta)[\s\S]{0,60}?['"]00[A-Za-z0-9_-]{40}['"]/gi,
  },
  {
    id: "dropbox-token",
    name: "Dropbox Access Token",
    severity: "high",
    description: "Dropbox OAuth 2 access token.",
    regex: /\bsl\.[A-Za-z0-9_-]{135,}\b/g,
  },
  {
    id: "linear-api-key",
    name: "Linear API Key",
    severity: "high",
    description: "Linear.app API key.",
    regex: /\blin_api_[A-Za-z0-9]{40,}\b/g,
  },
  {
    id: "asana-token",
    name: "Asana Personal Access Token",
    severity: "high",
    description: "Asana PAT.",
    regex: /\b[0-9]\/[0-9]{16}:[a-f0-9]{32}\b/g,
  },
  {
    id: "intercom-access-token",
    name: "Intercom Access Token",
    severity: "high",
    description: "Intercom access token.",
    regex: /\bdG9rOi[A-Za-z0-9_-]{60,}\b/g,
  },
  {
    id: "hubspot-api-key",
    name: "HubSpot Private App Token",
    severity: "high",
    description: "HubSpot private app access token.",
    regex: /\bpat-(?:na|eu)1-[a-f0-9-]{36,}\b/g,
  },
  {
    id: "plaid-secret",
    name: "Plaid Secret",
    severity: "critical",
    description: "Plaid API secret (production can initiate real financial data access).",
    regex: /\b(?:plaid)[-_. ]?(?:secret|api[-_]?secret)['":=\s]+['"]?[a-f0-9]{30}['"]?/gi,
  },
  {
    id: "supabase-service-role",
    name: "Supabase Service Role Key",
    severity: "critical",
    description: "Supabase service_role JWT — bypasses Row-Level Security.",
    regex: /\beyJhbGciOi[A-Za-z0-9_-]*\.eyJ[A-Za-z0-9_-]*(?:service_role|supabase_admin)[A-Za-z0-9_-]*\.[A-Za-z0-9_-]+/g,
  },
]
