// scripts/refresh-popular-packages.ts
// Refresh popular package lists from upstream sources.
// Run: npx tsx scripts/refresh-popular-packages.ts
//
// Schedule: quarterly, or whenever a new typosquatting incident is in the news.
//
// Sources:
//   - npm: https://github.com/LeoDog896/npm-rank releases (raw.json)
//          Returns Array of Package objects ordered by popularity.
//   - PyPI: https://hugovk.dev/top-pypi-packages/top-pypi-packages.min.json
//          Returns { rows: [{ project, download_count }, ...] } ordered by downloads.
//
// Output:
//   - lib/data/popular-npm.json   (top NPM_LIMIT)
//   - lib/data/popular-pypi.json  (top PYPI_LIMIT)

import { writeFile } from "node:fs/promises";
import { join } from "node:path";

const NPM_TOP_URL =
  "https://github.com/LeoDog896/npm-rank/releases/latest/download/raw.json";

const PYPI_TOP_URL =
  "https://hugovk.dev/top-pypi-packages/top-pypi-packages.min.json";

const NPM_LIMIT = 5000;
const PYPI_LIMIT = 1000;

const OUT_DIR = join(process.cwd(), "lib", "data");

interface OutputPackage {
  name: string;
  rank: number;
}

interface OutputFile {
  meta: {
    ecosystem: string;
    source: string;
    generatedAt: string;
    count: number;
    note: string;
  };
  packages: OutputPackage[];
}

async function fetchJson(url: string): Promise<unknown> {
  const res = await fetch(url, {
    redirect: "follow",
    headers: { "User-Agent": "RepoGuard refresh-popular-packages" },
  });
  if (!res.ok) {
    throw new Error(`Fetch failed: ${url} -> ${res.status} ${res.statusText}`);
  }
  return res.json();
}

async function refreshNpm(): Promise<void> {
  console.log(`[npm] Fetching from ${NPM_TOP_URL}`);
  const raw = (await fetchJson(NPM_TOP_URL)) as Array<{ name?: string }>;

  if (!Array.isArray(raw)) {
    throw new Error("npm fetch did not return an array");
  }

  const packages: OutputPackage[] = [];
  for (let i = 0; i < raw.length && packages.length < NPM_LIMIT; i++) {
    const item = raw[i];
    if (item && typeof item.name === "string" && item.name.length > 0) {
      packages.push({ name: item.name, rank: packages.length + 1 });
    }
  }

  const out: OutputFile = {
    meta: {
      ecosystem: "npm",
      source: NPM_TOP_URL,
      generatedAt: new Date().toISOString(),
      count: packages.length,
      note: "Auto-generated by scripts/refresh-popular-packages.ts. Do not edit by hand.",
    },
    packages,
  };

  const path = join(OUT_DIR, "popular-npm.json");
  await writeFile(path, JSON.stringify(out, null, 2) + "\n", "utf-8");
  console.log(`[npm] Wrote ${packages.length} packages to ${path}`);
}

async function refreshPyPI(): Promise<void> {
  console.log(`[pypi] Fetching from ${PYPI_TOP_URL}`);
  const raw = (await fetchJson(PYPI_TOP_URL)) as {
    rows?: Array<{ project?: string; download_count?: number }>;
  };

  if (!raw || !Array.isArray(raw.rows)) {
    throw new Error("pypi fetch did not return expected { rows: [...] } shape");
  }

  const packages: OutputPackage[] = [];
  for (let i = 0; i < raw.rows.length && packages.length < PYPI_LIMIT; i++) {
    const row = raw.rows[i];
    if (row && typeof row.project === "string" && row.project.length > 0) {
      packages.push({ name: row.project, rank: packages.length + 1 });
    }
  }

  const out: OutputFile = {
    meta: {
      ecosystem: "pypi",
      source: PYPI_TOP_URL,
      generatedAt: new Date().toISOString(),
      count: packages.length,
      note: "Auto-generated by scripts/refresh-popular-packages.ts. Do not edit by hand.",
    },
    packages,
  };

  const path = join(OUT_DIR, "popular-pypi.json");
  await writeFile(path, JSON.stringify(out, null, 2) + "\n", "utf-8");
  console.log(`[pypi] Wrote ${packages.length} packages to ${path}`);
}

async function main(): Promise<void> {
  console.log("Refreshing popular package lists...");
  await refreshNpm();
  await refreshPyPI();
  console.log("Done.");
}

main().catch((err) => {
  console.error("Refresh failed:", err);
  process.exit(1);
});
